// Generated by CoffeeScript 1.3.3
(function() {

  window.EpicMvc.app$BaseDevl = {
    MODELS: {
      Tag: {
        "class": "TagExe$BaseDevl",
        inst: "bdT"
      }
    }
  };

}).call(this);
