// Generated by CoffeeScript 1.4.0
(function() {

  window.EpicMvc.app$react = {
    MODELS: {
      Tag: {
        "class": 'TagExe$react',
        inst: 'reactTagExe'
      }
    }
  };

}).call(this);
