// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var bootstrap, _log2,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  _log2 = function() {};

  bootstrap = (function() {

    function bootstrap(Epic, content_watch) {
      var _this = this;
      this.Epic = Epic;
      this.content_watch = content_watch;
      this.onPopState = __bind(this.onPopState, this);

      this.very_first = true;
      this.was_popped = false;
      this.was_modal = false;
      this.unloadMsgs = {};
      this.baseUrl = window.document.location.pathname;
      this.baseId = "epic-new-page";
      this.modalId = "epic-new-modal";
      this.basePage = '<div id="' + this.baseId + '"></div><div id="' + this.modalId + '"></div>';
      $('body').html(this.basePage);
      setTimeout((function() {
        return _this.onPopState(true);
      }), 0);
      window.onpopstate = this.onPopState;
      true;
    }

    bootstrap.prototype.UnloadMessage = function(ix, msg) {
      var new_msg, nm, rec;
      if (msg) {
        this.unloadMsgs[ix] = msg;
      } else {
        delete this.unloadMsgs[ix];
      }
      new_msg = (function() {
        var _ref, _results;
        _ref = this.unloadMsgs;
        _results = [];
        for (nm in _ref) {
          rec = _ref[nm];
          _results.push(rec);
        }
        return _results;
      }).call(this);
      new_msg = new_msg.length ? new_msg.join("\n") : null;
      return window.onbeforeunload = function() {
        return new_msg;
      };
    };

    bootstrap.prototype.getFormData = function() {
      return $('form').serializeArray();
    };

    bootstrap.prototype.form_action = function(out_attrs, click_index, action, value) {
      var o;
      return o = "<button " + (out_attrs.join(' ')) + " onclick=\"EpicMvc.Epic.click(" + click_index + ");return false;\">" + value + "</button>";
    };

    bootstrap.prototype.link_action = function(click_index, id, attr_text, text) {
      var o;
      return o = "<a" + id + " href=\"#\" onclick=\"EpicMvc.Epic.click(" + click_index + ");return false;\"" + attr_text + ">" + text + "</a>";
    };

    bootstrap.prototype.doControl = function(oFi, c_nm, val, c_ty, c_data, wd, mx_len, do_one_radio) {
      var attrs, btn_id, button, choice_option, choice_value, choices, from_id, html, i, id, inputs, msg_id, msgs, s, size, split, to_id, _i, _j, _len, _ref, _ref1;
      html = '';
      c_ty = c_ty.split(':')[0];
      if (c_ty === 'radio' && do_one_radio) {
        c_ty = 'do_one_radio';
      }
      if (val == null) {
        val = '';
      }
      switch (c_ty) {
        case 'upload':
          id = 'U' + this.Epic.nextCounter();
          from_id = 'fr' + id;
          to_id = 'to' + id;
          btn_id = 'bt' + id;
          msg_id = 'ms' + id;
          button = "<span data-theme=\"a\" class=\"ui-btn ui-btn-corner-all ui-shadow ui-btn-up-a\" aria-disabled=\"false\" id=\"" + btn_id + "\">\n<span class=\"ui-btn-inner ui-btn-corner-all\" aria-hidden=\"true\">\n<span class=\"ui-btn-text\">Upload</span></span></span>";
          msgs = "<span class=\"qq-message\" id=\"" + msg_id + "\">" + (oFi.getUploadedMsg(c_nm, val)) + "</span>";
          inputs = "<input class=\"ui-input-text\" type=\"file\" style=\"display:none\" id=\"" + from_id + "\" name=\"upload_" + c_nm + "\" value=\"" + val + "\" size=\"" + wd + "\">\n<input type=\"hidden\" id=\"" + to_id + "\" name=\"" + c_nm + "\" value=\"" + val + "\">";
          html = "<table style=\"display:inline-block; width:60%\">\n	<tr>\n		<td style=\"width:120px\">" + button + "</td>\n		<td>" + msgs + "</td>\n		<td>" + inputs + "</td>\n	</tr>\n</table>";
          oFi.haveUpload(c_nm, from_id, to_id, btn_id, msg_id);
          break;
        case 'textarea':
          attrs = " name=\"" + c_nm + "\"";
          split = c_data.split(' ');
          for (i = _i = 0, _ref = split.length; _i < _ref; i = _i += 2) {
            attrs += ' ' + split[i].toLowerCase() + '="' + split[i + 1] + '"';
          }
          html += "<textarea" + attrs + ">" + (window.EpicMvc.escape_html(val)) + "</textarea>";
          break;
        case 'password':
        case 'text':
          html += "<input class=\"ui-input-text\" type=\"" + (c_ty.toLowerCase()) + "\" name=\"" + c_nm + "\" value=\"" + val + "\" size=\"" + wd + "\">";
          break;
        case 'do_one_radio':
        case 'radio':
          break;
        case 'pulldown':
          choices = oFi.getChoices(c_nm);
          size = wd ? " size=\"" + wd + "\"" : '';
          html = "<select name=\"" + c_nm + "\"" + size + " data-native-menu=\"false\">";
          _ref1 = choices.options;
          for (i = _j = 0, _len = _ref1.length; _j < _len; i = ++_j) {
            choice_option = _ref1[i];
            choice_value = choices.values[i];
            s = choice_value === val ? ' selected="selected"' : '';
            html += "\n<option value=\"" + (window.EpicMvc.escape_html(choice_value)) + "\"" + s + ">\n	" + (window.EpicMvc.escape_html(choice_option)) + "</option>";
          }
          html += "\n</select>";
      }
      return html;
    };

    bootstrap.prototype.onPopState = function(event) {
      var f, req_inx;
      f = 'E:bootstrap.onPopState: ';
      _log2(f, {
        was_popped: this.was_popped,
        very_first: this.very_first,
        special: event === true
      });
      if (event === true) {
        if (this.was_popped || !this.very_first) {
          return;
        }
      }
      this.was_popped = true;
      if (this.very_first) {
        req_inx = this.Epic.request().addLink({
          _a: 'browser_hash',
          hash: location.hash.substr(1)
        });
        this.Epic.click(req_inx);
      } else {
        if (event.state) {
          this.Epic.setModelState(event.state);
        }
        this.Epic.renderSecure();
      }
    };

    bootstrap.prototype.render = function(content, history, click_index, modal) {
      var container, f, watch, _i, _len, _ref,
        _this = this;
      f = 'E:bootstrap.render2: ';
      _log2(f, history, modal, this.was_modal);
      if (typeof history === 'undefined') {
        throw new Error('History is hosed!');
      }
      if (this.was_modal) {
        window.$('#' + this.modalId + '>div').modal('hide');
        $('#' + this.modalId).html('');
      }
      if (modal) {
        container = '#' + this.modalId;
        $(container).html(content);
        window.$('#' + this.modalId + ' div.modal').modal().on('hidden', function() {
          return _this.Epic.makeClick(false, 'close_modal', {}, true);
        });
      } else {
        container = '#' + this.baseId;
        $(container).html(content);
      }
      _ref = this.content_watch;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        watch = _ref[_i];
        watch(container);
      }
      this.handleRenderState(history, click_index);
      this.was_modal = modal;
      this.was_popped = false;
      this.very_first = false;
    };

    bootstrap.prototype.handleRenderState = function(history, click_index) {
      var displayHash, f, model_state, new_hash, _base, _base1;
      f = 'E:bootstrap.handleRenderState:' + history + ':' + click_index;
      _log2(f, {
        vf: this.very_first,
        wp: this.was_popped
      });
      if (!history) {
        return;
      }
      displayHash = this.very_first ? '' : 'click-' + click_index;
      new_hash = this.Epic.getDomCache();
      if (new_hash === false) {
        new_hash = this.Epic.getExternalUrl();
      }
      if (new_hash !== false) {
        displayHash = new_hash;
      }
      model_state = this.Epic.getModelState();
      if (this.very_first || history === 'replace') {
        if (typeof (_base = window.history).replaceState === "function") {
          _base.replaceState(model_state, displayHash, '#' + displayHash);
        }
      } else if (!this.was_popped && history === true) {
        if (typeof (_base1 = window.history).pushState === "function") {
          _base1.pushState(model_state, displayHash, '#' + displayHash);
        }
        window.document.title = displayHash;
      }
    };

    return bootstrap;

  })();

  window.EpicMvc.Extras.bootstrap$bootstrap = bootstrap;

}).call(this);
