// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var CoreModelJS, ModelJS,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CoreModelJS = window.EpicMvc.ModelJS;

  ModelJS = (function(_super) {

    __extends(ModelJS, _super);

    function ModelJS() {
      return ModelJS.__super__.constructor.apply(this, arguments);
    }

    ModelJS.prototype.action = function(act, parms) {
      window.alert("Unknown action (" + act + ") for model-name (" + this.view_nm + ").");
    };

    ModelJS.prototype.loadTable = function(tbl_nm) {
      if (tbl_nm in this.Table) {
        return;
      }
      window.alert("Model " + this.view_nm + ".loadTable needs (" + tbl_nm + ")");
      return this.Table[tbl_nm] = [{}];
    };

    ModelJS.prototype.fistLoadData = function(oFist) {
      window.alert("Model (" + this.view_nm + ").fistLoadData() needs (" + (oFist.getFistNm()) + ")");
    };

    ModelJS.prototype.fistGetFieldChoices = function(oFist, field) {
      window.alert("Model (" + this.view_nm + ").fistGetFieldChoices() needs (" + (oFist.getFistNm()) + ":" + field + ")");
    };

    return ModelJS;

  })(CoreModelJS);

  window.EpicMvc.ModelJS = ModelJS;

}).call(this);
