// Generated by CoffeeScript 1.4.0
(function() {

  E.app$FistDevl = {
    MANIFEST: {
      Model: ['Fist']
    },
    MODELS: {
      Fist: {
        "class": "Fist$FistDevl",
        inst: "iFistDevl_Fist"
      }
    },
    CLICKS: {
      F$change: {
        "do": 'Fist.F$change'
      }
    }
  };

}).call(this);
