// Generated by CoffeeScript 1.4.0
(function() {
  var LoadStrategy$Base;

  LoadStrategy$Base = (function() {

    function LoadStrategy$Base() {}

    LoadStrategy$Base.prototype.getArtifact = function(nm, type) {
      var i, pkg, results, _i, _len, _ref, _ref1, _ref2, _ref3, _ref4;
      results = false;
      if ((_ref = this.reverse_packages) == null) {
        this.reverse_packages = (function() {
          var _i, _ref1, _results;
          _results = [];
          for (i = _i = _ref1 = E.appconfs.length - 1; _ref1 <= 0 ? _i <= 0 : _i >= 0; i = _ref1 <= 0 ? ++_i : --_i) {
            _results.push(E.appconfs[i]);
          }
          return _results;
        })();
      }
      _ref1 = this.reverse_packages;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        pkg = _ref1[_i];
        results = (_ref2 = (_ref3 = E['view$' + pkg]) != null ? (_ref4 = _ref3[type]) != null ? _ref4[nm] : void 0 : void 0) != null ? _ref2 : false;
        if (results !== false) {
          break;
        }
      }
      if (results === false) {
        console.log('NO FILE FOUND! ' + nm);
      }
      return results;
    };

    LoadStrategy$Base.prototype.getAppConfs = function() {
      var pkg, result, _i, _len, _ref;
      result = [];
      _ref = E.appconfs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pkg = _ref[_i];
        result.push(E['app$' + pkg]);
      }
      return result;
    };

    LoadStrategy$Base.prototype.fist = function(grp_nm) {
      return E['fist$' + grp_nm];
    };

    LoadStrategy$Base.prototype.layout = function(nm) {
      return this.getArtifact(nm, 'tmpl');
    };

    LoadStrategy$Base.prototype.page = function(nm) {
      return this.getArtifact(nm, 'page');
    };

    LoadStrategy$Base.prototype.part = function(nm) {
      return this.getArtifact(nm, 'part');
    };

    return LoadStrategy$Base;

  })();

  E.Extra.LoadStrategy$Base = LoadStrategy$Base;

}).call(this);
