// Generated by CoffeeScript 1.4.0
(function() {
  var Push,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Push = (function() {

    function Push(io, host, port, push_url) {
      this._onUpdate = __bind(this._onUpdate, this);

      var f;
      f = 'Push:';
      this.handlers = {};
      this.socket = io.connect('http://' + host + ':' + port + '/' + push_url);
      this.socket.on('connected', this._onConnected);
      this.socket.on('update', this._onUpdate);
    }

    Push.prototype.sync = function(push_handle, syncFunc) {
      var f;
      f = 'Push:sync:';
      _log2(f, push_handle);
      this.handlers[push_handle] = syncFunc;
      return this.socket.emit('listen', push_handle);
    };

    Push.prototype._onConnected = function() {
      var f;
      f = 'Push:_onConnected:';
      return _log2(f, 'connected to server');
    };

    Push.prototype._onUpdate = function(data) {
      var f;
      f = 'Push:_onUpdate:';
      return this.handlers[data.push_handle](data.sync);
    };

    return Push;

  })();

  window.EpicMvc.Extras.Push = Push;

}).call(this);
