// Generated by CoffeeScript 1.4.0
(function() {

  E.app$Base = {
    OPTIONS: {
      render: 'RenderStrategy$Base',
      dataAction: 'dataAction$Base'
    },
    MODELS: {
      App: {
        "class": "App$Base",
        inst: "iBaseApp"
      },
      View: {
        "class": "View$Base",
        inst: "iBaseView"
      },
      Fist: {
        "class": "Fist$Base",
        inst: "iBaseFist"
      }
    }
  };

}).call(this);
