// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  E.manifest$Base = {
    Extra: ['LoadStrategy', 'RenderStrategy', 'dataAction', 'RestAPI'],
    Model: ['App', 'View', 'Fist', 'Wist', 'Tab'],
    js: [],
    root: ['app']
  };

}).call(this);
