// Generated by CoffeeScript 1.4.0
(function() {

  E.manifest$Base = {
    Extra: ['LoadStrategy', 'RenderStrategy', 'dataAction'],
    Model: ['App', 'View', 'Fist'],
    js: [],
    root: ['app']
  };

}).call(this);
