#!/bin/sh -e

EpicMvc=$1
MinOut=$2

for FILE in mithril
do
  echo -n "$FILE "
  cat $EpicMvc/${FILE}.js >> $MinOut
  echo >> $MinOut
done

for FILE in EpicCore
do
  echo -n "$FILE "
  echo -ne "/*${FILE}*/" >> $MinOut
  cat $EpicMvc/${FILE}.coffee | coffee --compile --stdio >> $MinOut
  echo >> $MinOut
done
echo done.
