#!/bin/sh

EpicMvc=$1
MinOut=$2

for FILE in Epic util ModelJS Issue Request AppConf ClickAction ConfExe ViewExe FistGroupCache Fist FistFilt parse
do
  echo -n "$FILE "
  echo -ne "/*${FILE}*/" >> $MinOut
  cat $EpicMvc/${FILE}.coffee | coffee --compile --stdio >> $MinOut
  echo >> $MinOut
done
echo done.
