#!/bin/sh -e
# JCS: Added |sort to make order of files deterministic so I can diff the results

DevHtmlPkg=$1
MinOut=$2

COFFEE=''
for FILE in `find -H $DevHtmlPkg -maxdepth 1 -name \*.coffee |sort |grep -vi manifest`  ; do COFFEE="$COFFEE $FILE" ; done
JSS=''
if [ -d $DevHtmlPkg/js ]
then
  for FILE in `find -H $DevHtmlPkg/js -name \*.js |sort` ; do JSS="$JSS $FILE" ; done
fi
for DIR in Model Extra
do
  if [ -d $DevHtmlPkg/$DIR ]
  then
    for FILE in `find -H $DevHtmlPkg/$DIR -name \*.coffee |sort` ; do COFFEE="$COFFEE $FILE" ; done
  fi
done

if [ -z "$COFFEE$JSS" ]
then
  echo 'No coffee or js source found'
  exit 1
fi

if [ -f $DevHtmlPkg/copyright.js ]
then
  cat $DevHtmlPkg/copyright.js >> $MinOut
fi

echo -n ':JavaScript: '
for ONE_FILE in $JSS
do
  A_FILE=`echo $ONE_FILE | grep -o [^/]*$`
  echo -n "$A_FILE "
  E_FILE=`echo $ONE_FILE | grep -o [^/]*/[^/]*$`
  echo -ne "/*$E_FILE*/" >> $MinOut
  uglifyjs -m --comments all $ONE_FILE >> $MinOut # Don't skip copyright notice, at the top, as a comment (i.e. not -nc)
  echo >> $MinOut
done
echo done.

echo -n ':CoffeeScript: '
for ONE_FILE in $COFFEE
do
  A_FILE=`echo $ONE_FILE | grep -o [^/]*/[^/]*$ | cut -d. -f1`
  echo -n "$A_FILE "
  E_FILE=`echo $ONE_FILE | grep -o [^/]*/[^/]*$`
  echo -ne "/*$E_FILE*/" >> $MinOut
  cat $ONE_FILE | grep -vE "\s(f= ['\"])|(E.log f)" |grep -v "#%#" | coffee --compile --stdio |uglifyjs -m >> $MinOut
  echo >> $MinOut
done
echo done.

