#!/bin/sh

# TODO More logic to check user error
# $3 must be a dir under $1/Package and $2/Package

DevHtml=$1
MinHtml=$2
Pkg=$3

Stage0=tmp0
#Stage1=$MinHtml/Package/$Pkg/tmp # Use this one to leave non-uglified source for debugging the compression step
Stage1=tmp1
StageM=$MinHtml/Package/$Pkg/min

if [ ! -d $MinHtml/Package ] ; then mkdir $MinHtml/Package ; fi

if [ -d $MinHtml/Package/$Pkg ] ; then rm -r $MinHtml/Package/$Pkg ; fi
cp -r $DevHtml/Package/$Pkg $MinHtml/Package/.
rm -rf $MinHtml/Package/$Pkg/{Extras,Model,view,*.coffee}

COFFEE=''
for DIR in Model Extras
do
  if [ -d $DevHtml/Package/$Pkg/$DIR ]
  then
    for FILE in `find $DevHtml/Package/$Pkg/$DIR -name \*.coffee` ; do COFFEE="$COFFEE $FILE" ; done
  fi
done

if [ -z "$COFFEE" ]
then
  echo 'No coffee source found'
  exit
fi

cat $COFFEE | grep -v "'use strict'" > $Stage0.coffee
coffee -c $Stage0.coffee
if [ -f $DevHtml/Package/$Pkg/copyright.js ]
then
  cat $DevHtml/Package/$Pkg/copyright.js $Stage0.js > $Stage1.js
else
  cp $Stage0.js $Stage1.js
fi
uglifyjs $Stage1.js > $StageM.js
rm $Stage0.{js,coffee}
