// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var Epic, deep_extend,
    __slice = [].slice;

  Epic = (function() {

    function Epic() {
      this.oAppConf = null;
      this.oFistGroupCache = null;
      this.getFistGroupCache = function() {
        return this.oFistGroupCache;
      };
      this.oModel = {};
      this.oFist = {};
      this.counter = 0;
      this.guard_run = false;
      this.inClick = false;
      this.wasModal = false;
      this.modelState = {};
      this.content_watch = [];
      this.click_path_changed = {};
      this.options = {
        click_warning_text: 'WARNING: Still processing previous click event (check for javascript errors.)'
      };
    }

    Epic.prototype.nextCounter = function() {
      return ++this.counter;
    };

    Epic.prototype.getPageflowPath = function() {
      return this.getInstance('Pageflow').getStepPath().join('/');
    };

    Epic.prototype.getInstanceNm = function(view_nm) {
      var inst_nm;
      return inst_nm = this.oAppConf.getObj(view_nm, 'inst');
    };

    Epic.prototype.getInstance = function(view_nm) {
      var cls, inst_nm;
      inst_nm = this.oAppConf.getObj(view_nm, 'inst');
      if (!(inst_nm in this.oModel)) {
        cls = this.oAppConf.getObj(view_nm, 'class');
        if (!(window.EpicMvc.Model[cls] != null)) {
          alert(":Epic.getInstance: (app.js) MODELS: " + view_nm + ": class: " + cls + " [(" + cls + ") not in window.EpicMvc.Model]");
        }
        this.oModel[inst_nm] = new window.EpicMvc.Model[cls](this, view_nm);
        if (inst_nm in this.modelState) {
          this.oModel[inst_nm].restoreState(this.modelState[inst_nm]);
        }
      }
      return this.oModel[inst_nm];
    };

    Epic.prototype.getViewTable = function(view_tbl_nm) {
      var a;
      a = view_tbl_nm.split('/');
      return this.getInstance(a[0]).getTable(a[1]);
    };

    Epic.prototype.getLookaheadClick = function(planned_action) {
      var sp;
      sp = this.getInstance('Pageflow').getStepPath();
      return this.oAppConf.findClick(sp, planned_action);
    };

    Epic.prototype.getDomCache = function() {
      var attr, sp;
      sp = this.getInstance('Pageflow').getStepPath();
      attr = this.oAppConf.getS(sp[0], sp[1], sp[2]).dom_cache;
      if (typeof attr === 'string') {
        return attr;
      }
      return false;
    };

    Epic.prototype.getExternalUrl = function() {
      var a, attr, sp;
      sp = this.getInstance('Pageflow').getStepPath();
      attr = this.oAppConf.getS(sp[0], sp[1], sp[2]).url;
      if (typeof attr !== 'string') {
        return false;
      }
      a = attr.split('/');
      return this.getInstance(a[0]).action(a[1], {})[0].url;
    };

    Epic.prototype.getGroupNm = function() {
      var oPf, t, ts, _ref;
      oPf = this.getInstance('Pageflow');
      _ref = oPf.getTrackPath(), ts = _ref[0], t = _ref[1];
      return this.oAppConf.getGroupNm(ts, t);
    };

    Epic.prototype.getFistInstance = function(flist_nm, grp_nm) {
      var fist_nm, g, inst_nm, view_nm;
      g = grp_nm != null ? grp_nm : this.getGroupNm();
      fist_nm = this.getFistGroupCache().getCanonicalFist(g, flist_nm);
      inst_nm = "" + g + "_" + fist_nm;
      if (!(inst_nm in this.oFist)) {
        view_nm = this.oAppConf.getFistView(g, fist_nm);
        this.oFist[inst_nm] = new window.EpicMvc.Fist(this, g, fist_nm, view_nm, flist_nm);
      }
      return this.oFist[inst_nm];
    };

    Epic.prototype.Execute = function(va, params) {
      var action, oM, view_nm, _ref;
      _log2(':Execute', va, params);
      _ref = va.split('/'), view_nm = _ref[0], action = _ref[1];
      oM = this.getInstance(view_nm);
      return oM.action(action, params);
    };

    Epic.prototype.run = function(appconfs, artifact_load_strategy_class, render_class, content_watch, options) {
      var loader, nm, renderer;
      if (this.guard_run) {
        return true;
      }
      this.guard_run = true;
      for (nm in options) {
        this.options[nm] = nm;
      }
      loader = new window.EpicMvc.Extras[artifact_load_strategy_class](this);
      renderer = new window.EpicMvc.Extras[render_class](this, content_watch);
      return this.init(appconfs, loader, renderer, content_watch);
    };

    Epic.prototype.init = function(appconfs, loader, renderer, content_watch) {
      var flow;
      this.appconfs = appconfs;
      this.loader = loader;
      this.renderer = renderer;
      this.content_watch = content_watch;
      this.oFistGroupCache = new window.EpicMvc.FistGroupCache(this, this.loader);
      this.oAppConf = new window.EpicMvc.AppConf(this, this.loader);
      flow = this.oAppConf.loginF();
      (this.getInstance('Pageflow')).goTo(flow);
      return true;
    };

    Epic.prototype.isSecurityError = function(e) {
      var special, _ref;
      special = 'Security';
      if (((e != null ? (_ref = e.message) != null ? _ref.substring : void 0 : void 0) != null) && (e.message.substring(0, special.length)) === special) {
        return true;
      }
      return false;
    };

    Epic.prototype.getFormData = function() {
      return this.renderer.getFormData();
    };

    Epic.prototype.renderStrategy = function(content, history, click_index, modal) {
      if (content !== false) {
        this.renderer.render(content, history, click_index, modal);
      } else {
        this.renderer.handleRenderState(history, click_index);
      }
      return null;
    };

    Epic.prototype.render = function(layout, sp, avoid_form_reset) {
      var history, k, modal, o, oView, page, stuff, _ref;
      page = this.oAppConf.getPage(sp);
      modal = this.oAppConf.findAttr(sp[0], sp[1], sp[2], 'modal');
      if (modal) {
        layout = this.oAppConf.mapModalLayout(modal);
      }
      history = (function() {
        switch ("" + (this.wasModal ? 1 : 0) + ":" + (modal ? 1 : 0)) {
          case '0:0':
            return true;
          case '1:0':
            return 'replace';
          case '0:1':
            return false;
          case '1:1':
            return false;
          default:
            return alert('my code is hosed');
        }
      }).call(this);
      oView = this.getInstance('View');
      oView.init(layout, page);
      try {
        stuff = oView.run();
      } catch (e) {
        _log2(':render error', e, e.stack);
        if (this.isSecurityError(e)) {
          return e;
        } else {
          this.inClick = false;
          throw e;
        }
      }
      this.renderStrategy(stuff, history, this.inClick, modal);
      if (avoid_form_reset !== true) {
        _ref = this.oFist;
        for (k in _ref) {
          o = _ref[k];
          if (typeof o.eventInitializePage === "function") {
            o.eventInitializePage();
          }
        }
      }
      this.wasModal = modal;
      return true;
    };

    Epic.prototype.login = function() {
      var f, k, o, _ref, _results;
      f = ':login';
      _log2(f, this.oModel);
      _ref = this.oModel;
      _results = [];
      for (k in _ref) {
        o = _ref[k];
        if (typeof o.eventLogin === "function" ? o.eventLogin() : void 0) {
          continue;
        }
      }
      return _results;
    };

    Epic.prototype.logout = function(click_event, click_data) {
      var k, o, _ref,
        _this = this;
      if (this.inClick !== false) {
        setTimeout((function() {
          return _this.logout(click_event, click_data);
        }), 100);
        return;
      }
      if (click_event) {
        this.makeClick(false, click_event, click_data, true);
      }
      _ref = this.oModel;
      for (k in _ref) {
        o = _ref[k];
        if (!(typeof o.eventLogout === "function" ? o.eventLogout() : void 0)) {
          continue;
        }
        delete this.modelState[k];
        delete this.oModel[k];
      }
      return this.oFist = {};
    };

    Epic.prototype.makeClick = function(form_flag, action, params, render_flag) {
      var click_index, f, p_action;
      f = ':makeClick:' + action;
      _log2(f, 'form?' + (form_flag ? 'Y' : 'N'), 'render' + (render_flag ? 'Y' : 'N'), params);
      p_action = {};
      p_action[form_flag ? '_b' : '_a'] = action;
      click_index = this.oRequest.addLink($.extend(p_action, params));
      this.click(click_index, !render_flag);
      return click_index;
    };

    Epic.prototype.click = function(action_token, data, no_render) {
      var action_attrs, after_sp, before_sp, click_result, f, first_node, k, o, oC, oPf, planned_action, ss, _ref, _ref1, _ref2;
      f = ':click';
      _log2(f, action_token, data);
      if (this.inClick !== false && this.options.click_warning_text !== false) {
        alert(this.options.click_warning_text);
      }
      oPf = this.getInstance('Pageflow');
      before_sp = oPf.getStepPath();
      if (action_token && no_render !== true) {
        planned_action = action_token;
        if (planned_action) {
          first_node = this.oAppConf.findClick(before_sp, planned_action);
        }
        if (first_node && (first_node.hasAttr('dynamic')) === true) {
          no_render = true;
        }
        _log2(f, 'render?', {
          no_render: no_render,
          sp: before_sp,
          action: planned_action,
          node: first_node
        });
      }
      if (!no_render) {
        this.inClick = action_token;
      }
      _ref = this.oFist;
      for (k in _ref) {
        o = _ref[k];
        if (typeof o.eventNewRequest === "function") {
          o.eventNewRequest(this.click_path_changed);
        }
      }
      _ref1 = this.oModel;
      for (k in _ref1) {
        o = _ref1[k];
        if (typeof o.eventNewRequest === "function") {
          o.eventNewRequest(this.click_path_changed);
        }
      }
      oC = new window.EpicMvc.ClickAction(this);
      click_result = oC.click(action_token, data);
      after_sp = oPf.getStepPath();
      oPf.setIssues(click_result[0]);
      oPf.setMessages(click_result[1]);
      action_attrs = click_result[2];
      this.click_path_changed.flow = before_sp[0] !== after_sp[0];
      this.click_path_changed.track = this.click_path_changed.flow || before_sp[1] !== after_sp[1];
      this.click_path_changed.step = this.click_path_changed.track || before_sp[2] !== after_sp[2];
      this.modelState = {};
      _ref2 = this.oModel;
      for (k in _ref2) {
        o = _ref2[k];
        if ((o.saveState != null) && (ss = o.saveState())) {
          this.modelState[k] = ss;
        }
      }
      if (no_render !== true || this.click_path_changed.step) {
        this.renderSecure();
      } else {
        this.renderStrategy(false, 'replace', click_index);
      }
      return this.inClick = false;
    };

    Epic.prototype.renderSecure = function(avoid_form_reset) {
      var f, layout, oC, oPf, render_attempts, render_result, sp, _results;
      f = ':renderSecure';
      _log2(f, 'start, avoid_form_reset', avoid_form_reset);
      oC = new window.EpicMvc.ClickAction(this);
      oPf = this.getInstance('Pageflow');
      render_result = false;
      render_attempts = 3;
      _results = [];
      while (render_result !== true && --render_attempts > 0) {
        _log2(f, (render_result === true ? 'T' : render_result === false ? 'F' : render_result), render_attempts);
        sp = oPf.getStepPath();
        if (render_result !== false) {
          oC.click(render_result.message, sp);
        }
        sp = oPf.getStepPath();
        layout = this.oAppConf.findLayout(sp);
        _results.push(render_result = this.render(layout, sp, avoid_form_reset));
      }
      return _results;
    };

    Epic.prototype.getModelState = function() {
      return this.modelState;
    };

    Epic.prototype.setModelState = function(s) {
      var inst_nm, _base, _results;
      if (s != null) {
        this.modelState = s;
      }
      _results = [];
      for (inst_nm in this.oModel) {
        _results.push(typeof (_base = this.oModel[inst_nm]).restoreState === "function" ? _base.restoreState(this.modelState[inst_nm]) : void 0);
      }
      return _results;
    };

    return Epic;

  })();

  deep_extend = function() {
    var atype, dest, dup, otype, source, sources, stype, utype, _i, _len;
    dest = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    otype = '[object Object]';
    atype = '[object Array]';
    utype = 'undefined';
    stype = 'scalar';
    func[otype] = function(dest, source) {
      var ans, snm;
      if (typeof source !== otype) {
        return void 0;
      }
      for (snm in source) {
        ans = dup(dest[snm], source[snm]);
        if (ans !== void 0) {
          dest[snm] = ans;
        }
      }
      return void 0;
    };
    func[atype] = function(dest, source) {
      var ans, sinx;
      if (typeof want !== atype) {
        reutrn(void 0);
      }
      for (sinx in source) {
        ans = dup(dest[sinx], source[sinx]);
        if (ans !== void 0) {
          dest[sinx] = ans;
        }
      }
      return void 0;
    };
    func[utype] = function(was, want) {
      var _ref, _ref1;
      if ((_ref = typeof was) !== otype && _ref !== atype) {
        if ((_ref1 = typeof want) !== otype && _ref1 !== atype) {
          return want;
        }
        return was;
      }
      if (typeof was !== typeof want) {
        return was;
      }
    };
    func[stype] = function(was, want) {
      if (typeof want in func) {
        return want;
      }
      return was;
    };
    dup = function(dest, source) {
      var type;
      type = typeof dest;
      if (!(type in func)) {
        type = stype;
      }
      return func[typeof dest](dest, source);
    };
    for (_i = 0, _len = sources.length; _i < _len; _i++) {
      source = sources[_i];
      dup(dest, source);
    }
    return dest;
  };

  window.EpicMvc = {
    deep_extend: deep_extend,
    Extras: {},
    Model: {},
    Epic: new Epic()
  };

}).call(this);
