// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var ModelJS;

  ModelJS = (function() {

    function ModelJS(Epic, view_nm, ss) {
      this.Epic = Epic;
      this.view_nm = view_nm;
      this._ModelJS = {
        ss: ss || false
      };
      this.restoreState(false);
    }

    ModelJS.prototype.getTable = function(tbl_nm) {
      this.loadTableIf(tbl_nm);
      return this.Table[tbl_nm];
    };

    ModelJS.prototype.loadTableIf = function(tbl_nm) {
      if (!(tbl_nm in this.Table)) {
        return this.loadTable(tbl_nm);
      }
    };

    ModelJS.prototype.restoreState = function(copy_of_state) {
      if (this._ModelJS.ss != null) {
        $.extend(true, this, this._ModelJS.ss);
      }
      if (copy_of_state) {
        $.extend(true, this, copy_of_state);
      }
      return this.Table = {};
    };

    ModelJS.prototype.saveState = function() {
      var nm, ss, st;
      ss = this._ModelJS.ss;
      if (!ss) {
        return false;
      }
      st = {};
      for (nm in ss) {
        if (this[nm] !== ss[nm]) {
          st[nm] = this[nm];
        }
      }
      if ($.isEmptyObject(st)) {
        return false;
      }
      return $.extend(true, {}, st);
    };

    ModelJS.prototype.invalidateTables = function(tbl_nms) {
      var nm, _i, _len;
      if (tbl_nms === true) {
        tbl_nms = (function() {
          var _results;
          _results = [];
          for (nm in this.Table) {
            _results.push(nm);
          }
          return _results;
        }).call(this);
      }
      for (_i = 0, _len = tbl_nms.length; _i < _len; _i++) {
        nm = tbl_nms[_i];
        delete this.Table[nm];
      }
      return this.Epic.oView.invalidateTables(this.view_nm, tbl_nms);
    };

    return ModelJS;

  })();

  window.EpicMvc.ModelJS = ModelJS;

}).call(this);
