// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var Request;

  Request = (function() {

    function Request(Epic) {
      this.Epic = Epic;
      this.click_link = ['zero'];
      this.link = [];
    }

    Request.prototype.start = function(link_index) {
      var f, form_data, ix, name, sp, v, _base, _i, _len, _ref, _ref1;
      f = ':Request.start:' + link_index;
      this.link = this.click_link[link_index];
      if (this.link._b != null) {
        form_data = this.Epic.getFormData();
        for (_i = 0, _len = form_data.length; _i < _len; _i++) {
          v = form_data[_i];
          _ref = v.name.split('__'), name = _ref[0], ix = _ref[1];
          if (ix) {
            if ((_ref1 = (_base = this.link)[name]) == null) {
              _base[name] = {};
            }
            this.link[name][ix] = v.value;
          } else {
            this.link[v.name] = v.value;
          }
        }
        this.link._a = this.link._b;
      }
      this.Epic.log2(f, '@link', this.link);
      if ((sp = this.link.temp_page_flow) != null) {
        return this.Epic.getInstance('Pageflow').goTo(sp[0], sp[1], sp[2]);
      }
    };

    Request.prototype.addLink = function(link) {
      var r;
      r = this.click_link.length;
      link.temp_page_flow = this.Epic.getInstance('Pageflow').getStepPath();
      this.click_link.push(link);
      return r;
    };

    Request.prototype.haveAction = function() {
      var _ref;
      return (_ref = this.link._a) != null ? _ref : false;
    };

    Request.prototype.getAction = function() {
      return this.link._a;
    };

    Request.prototype.getValues = function() {
      return this.link;
    };

    return Request;

  })();

  window.EpicMvc.Request = Request;

}).call(this);
