// Generated by CoffeeScript 1.4.0
(function() {
  var err, warn;

  warn = function(str, o) {
    return console.warn("WARNING", str, o != null ? o : '');
  };

  err = function(str, o) {
    console.error("ERROR", str, o != null ? o : '');
    throw new Error("ERROR: " + str);
  };

  window.EpicMvc.app$Dev = {
    OPTIONS: {
      warn: warn,
      err: err,
      c1: function(inAction) {
        if (inAction !== false) {
          return warn("IN CLICK");
        }
      },
      a1: function(view_name, aModels) {
        if (view_name in aModels) {
          return;
        }
        err("Could not find model (" + view_name + ") in namespace E.Model", aModels);
      },
      a2: function(view_name, aModels, attribute) {
        if (attribute in aModels[view_name]) {
          return;
        }
        err("Could not find model (" + view_name + ") in namespace E.Model", aModels);
      },
      m1: function(view, model) {
        if (model["class"] in E.Model) {
          return;
        }
        err("Processing view (" + view + "), model-class (" + model["class"] + ") not in namespace E.Model", model);
      },
      m2: function(view_nm, act, parms) {
        err("Model (" + view_nm + ").action() didn't know action (" + act + ")");
      },
      m3: function(view_nm, tbl_nm, table) {
        if (tbl_nm in table) {
          return;
        }
        err("Model (" + view_nm + ").loadTable() didn't know table-name (" + tbl_nm + ")");
      },
      m4: function(view_nm, fistNm, row) {
        err("Model (" + view_nm + ").fistValidate() didn't know FIST (" + fistNm + ")");
      },
      m5: function(view_nm, fistNm, row) {
        err("Model (" + view_nm + ").fistGetValues() didn't know FIST (" + fistNm + ")");
      },
      m6: function(view_nm, fistNm, fieldNm, row) {
        err("Model (" + view_nm + ").fistGetChoices() did't know FIST-FIELD (" + fistNm + "-" + fieldNm + ")");
      },
      ca1: function(action_token, original_path, action_node) {
        if (action_node != null) {
          return;
        }
        warn("No app. entry for action_token (" + action_token + ") on path (" + original_path + ")");
      },
      ca2: function(action_token, original_path, nms, data, action_node) {
        var nm, _i, _len;
        for (_i = 0, _len = nms.length; _i < _len; _i++) {
          nm = nms[_i];
          if (!(nm in data)) {
            warn("Missing param (" + nm + ") for action (" + action_token + "), Path: " + original_path, {
              data: data,
              action_node: action_node
            });
          }
        }
      },
      ca3: function(action_token, original_path, action_node, aMacros) {
        if (action_node["do"] in aMacros) {
          return;
        }
        err("Missing (" + action_node["do"] + ") from MACROS; Action: (" + action_token + "), Path: (" + original_path + ")");
      },
      ca4: function(action_token, original_path, action_node, what) {
        if (action_node[what] in E.fistDef) {
          return;
        }
        err("Unknown Fist for '" + what + ":' " + action_node[what] + "); Action: (" + action_token + "), Path: (" + original_path + ")", {
          action_node: action_node
        });
      },
      fi1: function(fist) {
        var fistNm, model;
        fistNm = fist.nm;
        model = E.appFist(fistNm);
        if (!(model != null)) {
          err("FIST is missing: app.js requires MODELS: <model-name>: fists:[...,'" + fistNm + "']", {
            fist: fist
          });
        }
      },
      fi2: function(field) {
        var attr, filt, filtList, filtNm, type, _i, _j, _len, _len1, _ref;
        _ref = ['h2h', 'd2h', 'h2d', 'validate'];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          attr = _ref[_i];
          if (!(attr in field)) {
            continue;
          }
          type = attr === 'validate' ? 'VAL' : attr.toUpperCase();
          filtList = attr === 'h2h' ? field[attr] : [field[attr]];
          for (_j = 0, _len1 = filtList.length; _j < _len1; _j++) {
            filtNm = filtList[_j];
            if (filtNm && !((filt = 'fist' + type + '$' + filtNm) in E)) {
              err("Missing Fist Filter (E." + filt + ") in FIELD (" + field.fieldNm + ") for FIST (" + field.fistNm + ")", {
                field: field
              });
            }
          }
        }
      },
      fi3: function(field, val) {
        if (val != null) {
          return;
        }
        warn("FIST field value is undefined in FIELD (" + field.fieldNm + ") for FIST (" + field.fistNm + ")", {
          field: field
        });
      },
      fi4: function(type, fist, field) {
        err("Unknown pulldown/radio option (" + type + ") in FIELD " + field.fieldNm + " for FIST " + field.fistNm + ".", {
          field: field
        });
      },
      v1: function(val, spec) {
        err("Unknown variable specification/filter (#" + spec + ")");
        return val != null ? val : '';
      },
      w1: function(wistNm) {
        if (wistNm in E.wistDef) {
          return;
        }
        err("Unknown Wist (" + wistNm + ").");
      }
    },
    SETTINGS: {
      frames: {
        MMM_Dev: 'bdevl'
      }
    },
    MODELS: {
      Devl: {
        "class": "Devl$Dev",
        inst: "iDev_Devl"
      },
      View: {
        "class": "View$Dev",
        inst: "iDev_View"
      }
    },
    ACTIONS: {
      dbg_toggle: {
        "do": 'Devl.toggle',
        pass: 'what'
      },
      dbg_refresh: {
        "do": 'Devl.clear_cache'
      },
      dbg_open_model: {
        "do": 'Devl.open_model',
        pass: 'name'
      },
      dbg_open_table: {
        "do": 'Devl.open_table',
        pass: 'name'
      },
      dbg_open_subtable: {
        "do": 'Devl.open_subtable',
        pass: 'name'
      },
      dbg_close_subtable: {
        "do": 'Devl.close_subtable'
      },
      dbg_table_left: {
        "do": 'Devl.table_left'
      },
      dbg_table_right: {
        "do": 'Devl.table_right'
      },
      dbg_table_col_set: {
        "do": 'Devl.table_col_set',
        pass: 'col'
      },
      dbg_table_by_row: {
        "do": 'Devl.table_row_set'
      }
    }
  };

}).call(this);
